language: python
python:
  "3.7-dev"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install: 
  pip install -r requirements.txt
script: 
  python manage.py test
after_success:
  - coveralls
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
