language: python
python:
  - "3.7-dev"

install: 
  pip install -r requirements.txt
script: 
  - python manage.py test
after_success:
  - coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
