language: python
python:
  - "3.7-dev"

install: 
  pip install -r requirements.txt
script: 
  - python manage.py test
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter
